# base.yml

strategy:
  name: base
  description: "Default base strategy"
  indicators:
    moving_average:
      enable: true
      type: simple
      period: 20
    moving_average:
      enable: true
      type: exponential
      period: 50
    rsi:
      enable: true
      period: 14
    macd:
      enable: true
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger_bands:
      enable: true
      period: 20
      deviations: 2
    stochastic_oscillator:
      enable: true
      k_period: 14
      d_period: 3
      slowing: 3
    average_true_range:
      enable: true
      period: 14
    ichimoku_cloud:
      enable: true
      tenkan_sen_period: 9
      kijun_sen_period: 26
      senkou_span_b_period: 52
    on_balance_volume:
      enable: true
    relative_vigor_index:
      enable: true
      period: 14
    average_directional_index:
      enable: true
      period: 14
